version: "3.8"

services:
  # Qdrant vector database - only accessible within the container network
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant-server
    ports:
      # Only expose internally - no external ports
      - "6333" # REST API (internal only)
      - "6334" # gRPC API (internal only)
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      QDRANT__SERVICE__HTTP_PORT: 6333
      QDRANT__SERVICE__GRPC_PORT: 6334
    networks:
      - app-network
    profiles:
      - dev
      - prod

  # Rust backend server
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: ${BUILD_TARGET:-development}
    container_name: rust-backend
    ports:
      - "10801:8080" # Map internal 8080 to external 10802
    environment:
      - RUST_LOG=${RUST_LOG:-info}
      - QDRANT_URL=http://qdrant:6333 # Internal network connection
    volumes:
      # Dev profile: mount source for hot reload
      - ./backend:/app:rw
      - cargo_cache:/usr/local/cargo/registry
      - target_cache:/app/target
    networks:
      - app-network
    depends_on:
      - qdrant
    profiles:
      - dev
      - prod

volumes:
  qdrant_data:
  cargo_cache:
  target_cache:

networks:
  app-network:
    driver: bridge
