name: Deploy to VPS
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Copy files to VPS
        run: |
          # Create server directory on VPS if it doesn't exist
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.VPS_HOST }} "mkdir -p ~/server"

          # Remove old files and copy new ones
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.VPS_HOST }} "cd ~/server && rm -rf * .*[!.] 2>/dev/null || true"

          # Copy all files except .git and .gitea directories
          tar --exclude='.git' --exclude='.gitea' -czf - . | \
            ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.VPS_HOST }} \
            "cd ~/server && tar -xzf -"

      - name: Build and Deploy on VPS
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.VPS_HOST }} 'bash -l -c "
            cd ~/server

            # Ensure ~/.local/bin is in PATH for podman-compose
            export PATH=\"\$HOME/.local/bin:\$PATH\"

            echo \"=== Shell Environment Debug ===\"
            echo \"Current shell: \$0\"
            echo \"PATH: \$PATH\"

            # Verify environment variables are accessible
            echo \"\"
            echo \"=== Checking environment variables ===\"
            echo \"SERVER_PORT: \$SERVER_PORT\"
            echo \"GIT_USER: \$GIT_USER\"
            echo \"CLONE_FOLDER: \$CLONE_FOLDER\"
            echo \"VECTOR_STORAGE_FOLDER: \$VECTOR_STORAGE_FOLDER\"
            echo \"NOTES_REPO: \${NOTES_REPO:+[SET]}\"
            echo \"GIT_PAT: \${GIT_PAT:+[SET]}\"
            echo \"VOYAGE_API_KEY: \${VOYAGE_API_KEY:+[SET]}\"
            echo \"OPENAI_API_KEY: \${OPENAI_API_KEY:+[SET]}\"

            # Detect system architecture for Go build
            echo \"\"
            echo \"=== Architecture Detection ===\"
            ARCH=\$(uname -m)
            case \$ARCH in
              x86_64)
                export TARGETARCH=amd64
                ;;
              aarch64|arm64)
                export TARGETARCH=arm64
                ;;
              armv7l)
                export TARGETARCH=arm
                ;;
              *)
                export TARGETARCH=amd64
                echo \"Unknown architecture \$ARCH, defaulting to amd64\"
                ;;
            esac
            echo \"System architecture: \$ARCH\"
            echo \"Target Go architecture: \$TARGETARCH\"

            # Set defaults for optional variables if not set
            export CLONE_FOLDER=\"\${CLONE_FOLDER:-/app/clone}\"
            export VECTOR_STORAGE_FOLDER=\"\${VECTOR_STORAGE_FOLDER:-/app/vectors}\"
            export SERVER_PORT=\"\${SERVER_PORT:-22010}\"

            echo \"\"
            echo \"=== Stopping existing containers ===\"
            podman-compose -f podman-compose.prod.yml down 2>/dev/null || true

            # Clean up old containers and images
            echo \"Cleaning up old images...\"
            podman container prune -f || true
            podman image prune -f || true

            echo \"\"
            echo \"=== Building and starting containers ===\"
            podman-compose -f podman-compose.prod.yml up -d --build

            echo \"\"
            echo \"=== Waiting for services to start ===\"
            sleep 10

            echo \"\"
            echo \"=== Checking deployment status ===\"
            if podman-compose -f podman-compose.prod.yml ps | grep -q \"Up\"; then
              echo \"✅ Deployment successful - containers are running\"
              podman-compose -f podman-compose.prod.yml ps
            else
              echo \"❌ Deployment failed - containers not running\"
              echo \"Container logs:\"
              podman-compose -f podman-compose.prod.yml logs vex-backend || echo \"No logs available\"
              exit 1
            fi

            echo \"\"
            echo \"=== Health check ===\"
            for i in \$(seq 1 30); do
              if curl -f -s \"http://localhost:\$SERVER_PORT/health\" > /dev/null 2>&1; then
                echo \"✅ Health check passed - application is ready\"
                echo \"🚀 Application deployed successfully at http://localhost:\$SERVER_PORT\"
                exit 0
              fi
              echo \"Health check attempt \$i/30 - waiting...\"
              sleep 2
            done

            echo \"⚠️  Health check timeout - check application logs\"
            podman-compose -f podman-compose.prod.yml logs --tail=50 vex-backend
          "'

      - name: Verify deployment
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.VPS_HOST }} 'bash -l -c "
            cd ~/server

            # Ensure ~/.local/bin is in PATH for podman-compose
            export PATH=\"\$HOME/.local/bin:\$PATH\"

            echo \"=== Final deployment verification ===\"
            echo \"Container status:\"
            podman-compose -f podman-compose.prod.yml ps

            echo \"\"
            echo \"Recent application logs:\"
            podman-compose -f podman-compose.prod.yml logs --tail=20 vex-backend

            echo \"\"
            echo \"=== Deployment Summary ===\"
            if podman-compose -f podman-compose.prod.yml ps | grep -q \"Up\"; then
              echo \"✅ Success - VEX application is running\"
            else
              echo \"❌ Failure - VEX application is not running\"
              exit 1
            fi
          "'
